environment:
  name: test
  project: cdf-bootcamp-22-test
  type: test
  selected:
  - modules/bootcamp/data_foundation
  - modules/bootcamp/ice_cream_api
  - modules/bootcamp/use_cases/oee

variables:
  modules:
    bootcamp:
      CDF_PROJECT: cdf-bootcamp-22-test
      IDP_CLIENT_ID: ${IDP_CLIENT_ID} # replaced by .env
      IDP_CLIENT_SECRET: ${IDP_CLIENT_SECRET} # replaced by .env
      IDP_TENANT_ID: ${IDP_TENANT_ID} # replaced by .env
      # This is related to the cluster where the CDF project is hosted.
      CDF_URL: https://westeurope-1.cognitedata.com
      IDP_SCOPES: https://westeurope-1.cognitedata.com/.default
      IDP_TOKEN_URL: ${IDP_TOKEN_URL} # replaced by .env
      # Groups
      # OBJECT ID FOR TEST DATA DEVELOPER ENTRA GROUP
      data_developer_source_id: 6204e9c7-1f08-4e10-9d1b-87e94062c5db
      # OBJECT ID FOR TEST DATA PIPELINE OEE ENTRA GROUP
      data_pipeline_oee_source_id: a0c04fc3-b801-4670-b071-c33ec32cfefd
      # OBJECT ID FOR TEST ADMIN TK ENTRA GROUP
      readwrite_source_id: aacf0bdf-d7f6-4e73-b1f4-43729bade0a1
      # OBJECT ID FOR TEST ADMIN TK ENTRA GROUP
      readonly_source_id: aacf0bdf-d7f6-4e73-b1f4-43729bade0a1
      # OBJECT ID FOR TEST ICAPI EXTRACTORS ENTRA GROUP
      icapi_extractors_source_id: 5d468296-eca9-4162-a94b-6885c0cafd95
      # Client Ids
      data_pipeline_oee_client_id: ${DATA_PIPELINE_OEE_CLIENT_ID} # replaced by .env
      data_pipeline_oee_client_secret: ${DATA_PIPELINE_OEE_CLIENT_SECRET} # replaced by .env
      icapi_extractors_client_id: ${ICAPI_EXTRACTORS_CLIENT_ID} # replaced by .env
      icapi_extractors_client_secret: ${ICAPI_EXTRACTORS_CLIENT_SECRET} # replaced by .env
      # ice_cream_api:
      icapi_ds_external_id: ds_icapi

      use_cases:
        oee:
          uc_oee_ds_external_id: ds_uc_oee
